// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWw8V5O46UjBEgvsfEM0Lzr1l7n1Dy6PQ',
    appId: '1:1031316928123:web:543596a14f3da876ab14de',
    messagingSenderId: '1031316928123',
    projectId: 'planapp-a5ce5',
    authDomain: 'planapp-a5ce5.firebaseapp.com',
    storageBucket: 'planapp-a5ce5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLfjSRl3rYqYZyhAaezBcr-NvOUIPnzw',
    appId: '1:1031316928123:android:3b67495b5ef2d883ab14de',
    messagingSenderId: '1031316928123',
    projectId: 'planapp-a5ce5',
    storageBucket: 'planapp-a5ce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfHs1ud3lBN6L9-S9IsxhIXJz1r-9LfAA',
    appId: '1:1031316928123:ios:2c07121f1ec1d2bdab14de',
    messagingSenderId: '1031316928123',
    projectId: 'planapp-a5ce5',
    storageBucket: 'planapp-a5ce5.firebasestorage.app',
    iosBundleId: 'com.example.planapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfHs1ud3lBN6L9-S9IsxhIXJz1r-9LfAA',
    appId: '1:1031316928123:ios:2c07121f1ec1d2bdab14de',
    messagingSenderId: '1031316928123',
    projectId: 'planapp-a5ce5',
    storageBucket: 'planapp-a5ce5.firebasestorage.app',
    iosBundleId: 'com.example.planapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWw8V5O46UjBEgvsfEM0Lzr1l7n1Dy6PQ',
    appId: '1:1031316928123:web:0ef804661a8d4da2ab14de',
    messagingSenderId: '1031316928123',
    projectId: 'planapp-a5ce5',
    authDomain: 'planapp-a5ce5.firebaseapp.com',
    storageBucket: 'planapp-a5ce5.firebasestorage.app',
  );
}
